var fakeData = [
  {
    id: "01",
    name: "Online Training on IT Security & Ethical Hacking",
    description: "",
    instructor: "Edwin Saladino",
    price: 45,
    img: "https://i.ibb.co/Cwrtzqp/img1.png",
    hours: "12",
  },
  {
    id: "02",
    name: "Software Testing & Quality Assurance using Selenium",
    description: "",
    instructor: "Young Chapman",
    price: 40,
    img: "https://i.ibb.co/xDxVDC0/img5.jpg",
    hours: "08",
  },
  {
    id: "03",
    name: "Machine Learning with Python",
    description: "",
    instructor: "Harold Bates",
    price: 95,
    img: "https://i.ibb.co/Pg2d4bC/img6.jpg",
    hours: "300",
  },
  {
    id: "04",
    name: "Web Development with React & Node.js",
    description: "",
    instructor: "James Lewis",
    price: 60,
    img: "https://i.ibb.co/5Ts1MPy/img4.jpg",
    hours: "150",
  },
  {
    id: "05",
    name: "Online Training on Cisco Certified Network Associate (CCNA 200-301)",
    description: "",
    instructor: "Clyde Seese",
    price: 35,
    img:
      "https://i.ibb.co/hKbYTTC/Open-laptop-on-the-desk-with-a-title-online-study-on-the-screen-Education-concept-photo-view-over-th.jpg",
    hours: "36",
  },
  {
    id: "06",
    name: "Online Training on Agile Hands-on with Scrum Practices",
    description: "",
    instructor: "Daniel Reilly",
    price: 49.99,
    img: "https://i.ibb.co/Mh2VvL5/img2.jpg",
    hours: "24",
  },
  {
    id: "07",
    name: "Wodpress Theme Development",
    description: "",
    instructor: "Jasper Olson",
    price: 15.99,
    img: "https://i.ibb.co/Cwrtzqp/img1.png",
    hours: "08",
  },
  {
    id: "08",
    name: "Fullstack Modern Javascript Course",
    description: "",
    instructor: "Kevin Lukasik",
    price: 50,
    img: "https://i.ibb.co/xDxVDC0/img5.jpg",
    hours: "72",
  },
  {
    id: "09",
    name: "Web App Development with Laravel & Vue",
    description: "",
    instructor: "Larry Welch",
    price: 54.99,
    img: "https://i.ibb.co/Pg2d4bC/img6.jpg",
    hours: "96",
  },
  {
    id: "10",
    name: "Digital Marketing for Beginners",
    description: "",
    instructor: "Wilfred Jamerson",
    price: 12.55,
    img: "https://i.ibb.co/5Ts1MPy/img4.jpg",
    hours: "08",
  },
  {
    id: "11",
    name: "ERP Functional Workshop for Corporate Efficiency",
    description: "",
    instructor: "Edward Taylor",
    price: 20,
    img:
      "https://i.ibb.co/hKbYTTC/Open-laptop-on-the-desk-with-a-title-online-study-on-the-screen-Education-concept-photo-view-over-th.jpg",
    hours: "12",
  },
  {
    id: "12",
    name: "Cloud Journey with AWS (Beginner to Advance level)",
    description: "",
    instructor: "Brian Munoz",
    price: 44.99,
    img: "https://i.ibb.co/Mh2VvL5/img2.jpg",
    hours: "72",
  },
  {
    id: "13",
    name: "Web Hosting Server Installation and Maintenance",
    description: "",
    instructor: "Victor White",
    price: 10.99,
    img: "https://i.ibb.co/Cwrtzqp/img1.png",
    hours: "08",
  },
  {
    id: "14",
    name: "Professional Android Application Development",
    description: "",
    instructor: "Roy Auguste",
    price: 64.99,
    img: "https://i.ibb.co/xDxVDC0/img5.jpg",
    hours: "150",
  },
  {
    id: "15",
    name: "Certificate Course On Oracle DBA",
    description: "",
    instructor: "Derick Rangel",
    price: 25,
    img: "https://i.ibb.co/Pg2d4bC/img6.jpg",
    hours: "48",
  },
  {
    id: "16",
    name: "Certificate Course On Oracle DBA",
    description: "",
    instructor: "Sol Salazar",
    price: 25,
    img: "https://i.ibb.co/5Ts1MPy/img4.jpg",
    hours: "24",
  },
  {
    id: "17",
    name: "Microsoft Asp.net MVC Core With SQL Server 2017",
    description: "",
    instructor: "Gregory Rhone",
    price: 25,
    img:
      "https://i.ibb.co/hKbYTTC/Open-laptop-on-the-desk-with-a-title-online-study-on-the-screen-Education-concept-photo-view-over-th.jpg",
    hours: "24",
  },
  {
    id: "18",
    name: "Certificate Course On Oracle DBA",
    description: "",
    instructor: "Delbert Thompson",
    price: 24.55,
    img: "https://i.ibb.co/Mh2VvL5/img2.jpg",
    hours: "24",
  },
];

export default fakeData;
